# Generated by Django 5.0 on 2023-12-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_account_number_alter_user_government_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
