# Generated by Django 5.0 on 2023-12-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
