# Generated by Django 5.0 on 2024-01-10 20:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_account_number_remove_user_government_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='account_number',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('account_type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('balance', 'balance')], max_length=50)),
                ('transaction_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
    ]
