# Generated by Django 5.0 on 2024-01-04 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('monthly', 'monthly'), ('Yearly', 'Yearly'), ('Weekly', 'Weekly')], max_length=50),
        ),
    ]
